{% set name = "ffn" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 540b903f1ef0fbdc95fbe0b9aacfda775fa20bb661728b118fcf78606a3d3cf4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - decorator >=4
    - future >=0.15
    - matplotlib-base >=1
    - numpy >=1.5
    - pandas >=0.19
    - pandas-datareader >=0.2
    - scikit-learn >=0.15
    - scipy >=0.15
    - tabulate >=0.7.5
    - yfinance >=0.2
    - python >=3.6

test:
  imports:
    - ffn
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pmorissette/ffn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ffn - a financial function library for Python
  description: |
    ffn - a financial function library for Python
  doc_url: http://pmorissette.github.io/ffn/
  dev_url: https://github.com/pmorissette/ffn

extra:
  recipe-maintainers:
    - timkpaine
