schema_version: 1

context:
  name: ffn
  version: "1.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7ecf6cf5d33c1196d1d4e6be7a8f4231873becc9ea1bb0e2dd7ceb2c1200e4e8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - decorator >=5.0.7
    - future >=0.15
    - matplotlib-base >=1
    - numpy >=1.5
    - pandas >=0.19
    - scikit-learn >=0.15
    - scipy >=0.15
    - tabulate >=0.7.5
    - yfinance >=0.2
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - ffn
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: MIT
  license_file: LICENSE
  summary: ffn - a financial function library for Python
  description: |
    ffn - a financial function library for Python
  homepage: https://github.com/pmorissette/ffn
  repository: https://github.com/pmorissette/ffn
  documentation: http://pmorissette.github.io/ffn/

extra:
  recipe-maintainers:
    - timkpaine
